### PR TITLE
Api doc improvements

### PR DESCRIPTION
**Pull request by kalwalt**
This PR wiill add some missed description inside **artoolkit.api.js** needed for the jsdoc compilation.
For a list of missed functions see #17 
I will update also the README.md description (ARToolKit JS API) and after.

### CODE REVIEW

**Comment by kalwalt** [comment]
i deleted the last part of the Readme because was referring to a very old API of jsartoolkit5. I think was very confusing we could enhance instead the api doc. I think i added a basic descriptions for most of the functions, we could improve this in another PR after the merging in master.

**Comment by kalwalt** [comment]
@nicolocarpignoli @ThorstenBux If you think we can add other infos or we should make certain parts clearer, leave me a note here.

**Comment by kalwalt** [comment]
I added a link to the NFT-Marker-Creator @Carnaux but  maybe we can improve this part.

**Comment by Carnaux** [comment]
@kalwalt later we can add a link to the marker creator wiki

**Comment by kalwalt** [comment]
> @kalwalt later we can add a link to the marker creator wiki

Yes, or maybe i can add it already, I think you will do a good work...:smile:

**Comment by kalwalt** [comment]
i will leave the https://github.com/kalwalt/jsartoolkit5/tree/fixing-nft#constants in the Readme.md because i don't know how to add in the api docs. I think that the documentation can be improved in another PR when fixing-nft branch ill be merged.

**Pull request merged**
