### PR TITLE
WIP tests for NFT.

### PR DESCRIPTION
**Pull request by ThorstenBux**
ASM tests done WASM tests missing. Might need to rework WASM test file.

### CODE REVIEW

**Comment by kalwalt** [comment]
I'm testing this PR. I changed the line:
  https://github.com/ThorstenBux/jsartoolkit5/blob/1d06eef2422917136af17a23515c74409bd0c93f/tests/tests.js#L104

i changed from `skip` to `test` and line 112:

  ```diff
-assert.deepEqual(trackableInfo.marker.idMatrix,0);
+assert.deepEqual(trackableInfo.data.marker.idMatrix,0);
```
and all tests was ok. 
Regarding conflicting files maybe you should pull my recent commit from `fixing-nft` and should solve it.

**Comment by ThorstenBux** [comment]
Merged and pushed

The libraries need rebuild I guess but besides that it is ok.
I’m on the fence if we should keep the libs inside the repo or just make them available as GitHub release download. Having binaries inside the repo causes trouble usually.

**Comment by kalwalt** [comment]
@ThorstenBux Do you mean like for https://github.com/augmentmy-world/artoolkitX.js ?

**Comment by kalwalt** [comment]
Releasing as package in the Github download would be fine.  I think we should do in that way.  We can discuss this if you want. 
Anyway there are other conflicts to solve.

**Comment by ThorstenBux** [comment]
I’ll check

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by ThorstenBux** [comment]
should be fixed now

**Comment by ThorstenBux** [comment]
> Releasing as package in the Github download would be fine. I think we should do in that way. We can discuss this if you want.
> Anyway there are other conflicts to solve.

Once it is on artoolkitx/master the build would automatically kick in and release it on GitHub releases.

**Pull request merged**
