### PR TITLE
Build with docker

### PR DESCRIPTION
**Pull request by ThorstenBux**
This PR add the Docker support for the build system. Based on the discussion in the PR #1  and issues #11 #10 #12 
**[Docker](https://www.docker.com/)** is the recommended tool for building the libs.
- [x] added informations for building with **Docker** in the README.md file
- [x] added `-s USE_LIBJPEG` flag to the makem.js: by emscripten **v1.38.31** you can include libjpeg in the project without adding any libs or headers files.
- [x] removed the libjpeg.bc file and other part of libjpeg references in the makem.js node script.
- [x] updating istructions in [disencuraged-build-local-with-manual-emscripten-setup](https://github.com/ThorstenBux/jsartoolkit5/blob/build-with-docker/README.md#disencuraged-build-local-with-manual-emscripten-setup) section of the README.md
- [x] removed build.sh script
- [x] re-added the flag ' -s BINARYEN_TRAP_MODE=clamp' for nft + wasm compilation
- [x] other fixex in conf.json and package.json

### CODE REVIEW

**Comment by kalwalt** [comment]
@ThorstenBux In the README.md should be updated also the section [disencuraged-build-local-with-manual-emscripten-setup](https://github.com/ThorstenBux/jsartoolkit5/blob/build-with-docker/README.md#disencuraged-build-local-with-manual-emscripten-setup)
the 9 point should be:
```diff
+npm run build-local
-npm run build
```
and we can delete also the points 3 and 4 about libjpeg.

**Comment by kalwalt** [comment]
i tested also your latest changes https://github.com/kalwalt/jsartoolkit5/pull/13/commits/fa89ed234421d638b5502c0752e3b158fedf3d37 , as 
 i suggested in #12, with Docker and works perfectly!

**Comment by ThorstenBux** [comment]
Updated and pushed. You may have a look at it again and merge if you think it is good.

**Comment by kalwalt** [comment]
I think it is ok. We can go over, for other improves in the code. Thank you!

**Pull request merged**
