### PR TITLE
remove libjpeg compilation because libjpeg is provided by emscripten.…

### PR DESCRIPTION
**Pull request by ThorstenBux**
… Only read header files for compilation of artoolkit

### CODE REVIEW

**Comment by nicolocarpignoli** [comment]
seems good to me!

**Comment by kalwalt** [comment]
It works for me under Linux (ubuntu 18.04). We need to test under Windows OS, @Carnaux @misdake may you?
Thanks to everybody!

**Comment by kalwalt** [comment]
testing the examples i receive this error with **nft_threejs.html**:

﻿
```js
Live reload enabled.
artoolkit.min.js:35 [warning] *** Camera Parameter resized from 640, 480. ***
artoolkit.min.js:35 [info] Allocated videoFrameSize 4915200
three.min.js:184 THREE.WebGLRenderer 103
three.min.js:931 THREE.MeshNormalMaterial: .shading has been removed. Use the boolean .flatShading instead.
artoolkit.min.js:1 [Violation] 'load' handler took 908ms
730
[Violation] 'requestAnimationFrame' handler took <N>ms
artoolkit.min.js:35 [info] Reading /markerNFT_0.fset3
artoolkit.min.js:35 [info]   Assigned page no. 0.
artoolkit.min.js:35 [info]   Done.
artoolkit.min.js:35 [info] Reading /markerNFT_0.fset
artoolkit.min.js:35 [info] 
artoolkit.min.js:35 ### Surface No.1 ###
artoolkit.min.js:35 [info]   Read ImageSet.
artoolkit.min.js:35 [info] Imageset contains 9 images.
artoolkit.min.js:35 [error] Error reading JPEG file.
artoolkit.min.js:35 [warning] Falling back to reading '/markerNFT_0.iset' in ARToolKit v4.x format.
artoolkit.min.js:35 OOM
artoolkit.min.js:35 Uncaught Error: abort(OOM). Build with -s ASSERTIONS=1 for more info.
    at abort (artoolkit.min.js:35)
    at abortOnCannotGrowMemory (artoolkit.min.js:35)
    at _emscripten_resize_heap (artoolkit.min.js:35)
    at Le (artoolkit.min.js:9)
    at Qa (artoolkit.min.js:9)
    at eG (artoolkit.min.js:17)
    at hG (artoolkit.min.js:17)
    at VE (artoolkit.min.js:17)
    at _s (artoolkit.min.js:13)
    at Array.Os (artoolkit.min.js:13)

```

**Comment by kalwalt** [comment]
and pinball marker is not recognized...

**Comment by kalwalt** [comment]
i have the same result for the example with webworker.

**Comment by kalwalt** [comment]
it seems that only the NFT part of the code is affected by this issue... probably because is needed the libjpeg.a lib for linux, it is not present... i will try adding the static lib somewhere in the project just to test.

**Comment by kalwalt** [comment]
tested with this modification in makem.js:

```js
var ALL_BC
const platform = os.platform()
if (platform === 'linux') {
		ALL_BC = " {OUTPUT_PATH}libar.bc " + SOURCE_PATH + "libjpeg/libjpeg.a ";
	} else {
		ALL_BC = " {OUTPUT_PATH}libar.bc ";
	}
```
and added the libjpeg.a but fails with this error (partial log):

```js
Running command: /home/walter/emsdk/upstream/emscripten/emcc -I/home/walter/kalwalt-github/jsartoolkit5/emscripten/artoolkit5/include -I/home/walter/kalwalt-github/jsartoolkit5/build/ -I/home/walter/kalwalt-github/jsartoolkit5/emscripten/ -I/home/walter/kalwalt-github/jsartoolkit5/emscripten/artoolkit5/lib/SRC/KPM/FreakMatcher -I/home/walter/kalwalt-github/jsartoolkit5/emscripten/libjpeg  /home/walter/kalwalt-github/jsartoolkit5/build/libar.bc /home/walter/kalwalt-github/jsartoolkit5/emscripten//libjpeg/libjpeg.a /home/walter/kalwalt-github/jsartoolkit5/emscripten/ARToolKitJS.cpp /home/walter/kalwalt-github/jsartoolkit5/emscripten/trackingMod.c /home/walter/kalwalt-github/jsartoolkit5/emscripten/trackingMod2d.c -Oz  -Wno-warn-absolute-paths  -s TOTAL_MEMORY=268435456  -s USE_ZLIB=1 -s USE_LIBJPEG --memory-init-file 0  --bind  -s WASM=0  -g  -s ASSERTIONS=1  --profiling  -s ALLOW_MEMORY_GROWTH=1  -s DEMANGLE_SUPPORT=1   -D HAVE_NFT  -o /home/walter/kalwalt-github/jsartoolkit5/build/artoolkit.debug.js 

stderr: wasm-ld: error: unknown file type: jcapimin.c.o
shared:ERROR: '/home/walter/emsdk/upstream/bin/wasm-ld -o /tmp/emscripten_temp_BoU3Sm/artoolkit.debug.wasm --allow-undefined --lto-O0 /home/walter/kalwalt-github/jsartoolkit5/build/libar.bc /home/walter/kalwalt-github/jsartoolkit5/emscripten//libjpeg/libjpeg.a /tmp/emscripten_temp_BoU3Sm/ARToolKitJS_0.o /tmp/emscripten_temp_BoU3Sm/trackingMod_1.o /tmp/emscripten_temp_BoU3Sm/trackingMod2d_2.o -L/home/walter/emsdk/upstream/emscripten/system/local/lib -L/home/walter/emsdk/upstream/emscripten/system/lib -L/home/walter/.emscripten_cache/wasm-obj /home/walter/.emscripten_cache/wasm-obj/libjpeg.a /home/walter/.emscripten_cache/wasm-obj/libz.a /home/walter/.emscripten_cache/wasm-obj/libc.a /home/walter/.emscripten_cache/wasm-obj/libcompiler_rt.a /home/walter/.emscripten_cache/wasm-obj/libc-wasm.a /home/walter/.emscripten_cache/wasm-obj/libc++-noexcept.a --whole-archive /home/walter/.emscripten_cache/wasm-obj/libc++abi-noexcept.a /home/walter/.emscripten_cache/wasm-obj/libembind-rtti.a --no-whole-archive /home/walter/.emscripten_cache/wasm-obj/libdlmalloc-debug.a /home/walter/.emscripten_cache/wasm-obj/libpthread_stub.a /home/walter/.emscripten_cache/wasm-obj/libc_rt_wasm.a --import-memory --import-table -mllvm -combiner-global-alias-analysis=false -mllvm -enable-emscripten-sjlj -mllvm -disable-lsr --export __wasm_call_ctors --export __data_end --export main --export __cxa_demangle --export malloc --export free --export setThrew --export __errno_location --export fflush --export realloc --export _get_tzname --export _get_daylight --export _get_timezone --export _ZSt18uncaught_exceptionv --export _get_environ -z stack-size=5242880 --initial-memory=268435456 --no-entry --global-base=1024' failed (1)

exec error: 1
Built at lun 16 dic 2019, 15.00.12, CET
walter@walter-RC530-RC730:~/kalwalt-github/jsartoolkit5$ 

```

@ThorstenBux i think the libjpeg.a lib must be build under emscripten or not?

**Comment by kalwalt** [comment]
Probably this error is not caused by using  a different compiler but a different project, anyway i'm trying with libjpeg.bc instead.

**Comment by kalwalt** [comment]
adding the libjpeg.bc and this pesce of code solved the issue:

```js
var ALL_BC;
const platform = os.platform();
if (platform === 'linux') {
	ALL_BC = " {OUTPUT_PATH}libar.bc " + SOURCE_PATH + "libjpeg/libjpeg.bc ";
} else {
	ALL_BC = " {OUTPUT_PATH}libar.bc ";
			}
```
i will upload a libjpeg.bc file to my https://github.com/kalwalt/libjpeg-for-jsartoolkit5

**Comment by ThorstenBux** [comment]
Alright, thanks @kalwalt for investigating into that. Looks like the bytecode version of libjpeg is needed to build the final lib. I thought Emscripten would pull that in automatically. Learned different.

In that case I would say we add the build libjpeg.bc to the repo and reference it for the build. It shouldn't change anyways and that way not everyone needs to build it. 

@kalwalt you seem to have a working version. Can you please add the libjpeg.bc to the project and push that to the branch. Then I'll pull that and try to build on mac and let you know. Thank you

**Comment by kalwalt** [comment]
yes i will do soon!

**Pull request merged**
