### PR TITLE
Restoring nft with wasm - second version

### PR DESCRIPTION
**Pull request by kalwalt**
This PR restore the wasm example for NFT. The example **nft_threejs_wasm.html** already exist but wasn't working because it require:

`-s "BINARYEN_TRAP_MODE='clamp'"`

but it could be a problem for some emscripten versions (?) config (?). @nicolocarpignoli We need to investigate this.
The goal of this PR is also to develop another example with NFT + wasm + webworkers.
@misdake do you think is possible?

### Main to do list
- [x] adding wasm+worker+trheejs example
- [x] ~~solving the BINARYEN_TRAP_MODE=clamp issue adding an if conditional.~~
- [x] making a makem.js script cross paltform, not only for Linux and Mac but also for Windows.

Edit: the `BINARYEN_TRAP_MODE=clamp` is not needed anymore under linux see the comments above. To build the libraries i used latest emsdk emscripten with `upstream` at commit: https://github.com/emscripten-core/emsdk/commit/1e42b446510ad27489bce58e3952ccaf4803fc68
 in date (10/december/2019)

### CODE REVIEW

**Comment by misdake** [comment]
Now, I did some experiments to make it barely work in worker using your wasm build:
- add window.addEventListener/removeEventListener/dispatchEvent implementation to worker.js
- add "scope.Module=Module;" before "if(scope.Module)" in artoolkitNft_wasm.js, making sure event dispatching works.
- copy loaded jsartoolkit5 scope to webworker global variable (Object.assign(self, window);), so we do not need to change jsartoolkit5 references in worker.js
- start main thread initialization after wasm is loaded

Code:
[jsartoolkit-wasm.zip](https://github.com/kalwalt/jsartoolkit5/files/3935778/jsartoolkit-wasm.zip)

Demos:
[camera input, worker wasm, threejs](https://rgbuv.xyz/jsartoolkit_wasm/main_threejs_worker.html)
[video input, worker wasm, threejs](https://rgbuv.xyz/jsartoolkit_wasm/video_threejs_worker.html)

(also I built wasm version on windows without this BINARYEN_TRAP_MODE line, and run single-threaded version with no problem)

**Comment by kalwalt** [comment]
Thank you @misdake ☺️ i have no time for trying your code i will try later.  
BTw that' s strange that you don't need the BINARYEN_TRAP_MODE line, do you receive any error message while using your demo?
More to come when i tested the code...

**Comment by misdake** [comment]
@kalwalt 
I tried [my windows build](https://github.com/misdake/jsartoolkit5/tree/fixing-nft/build) and it works all right in this threejs demo. no error.

> I built js & wasm files in windows environment based on this modified makem.js file [here](https://gist.github.com/misdake/ec0f67c3f50b0b89229d8e70ed77c37d), based on [here](https://github.com/misdake/jsartoolkit5/blob/a6dd9a5554333953cd2d6aff6a6d5633f29a44ee/tools/makem.js). This modified file is not in this pr.

iirc this BINARYEN_TRAP_MODE line causes build to fail on windows. I had to build without it.

**Comment by kalwalt** [comment]
> @kalwalt
> I tried [my windows build](https://github.com/misdake/jsartoolkit5/tree/fixing-nft/build) and it works all right in this threejs demo. no error.
> BINARYEN_TRAP_MODE
> > I built js & wasm files in windows environment based on this modified makem.js file [here](https://gist.github.com/misdake/ec0f67c3f50b0b89229d8e70ed77c37d), based on [here](https://github.com/misdake/jsartoolkit5/blob/a6dd9a5554333953cd2d6aff6a6d5633f29a44ee/tools/makem.js). This modified file is not in this pr.
> 
> iirc this BINARYEN_TRAP_MODE line causes build to fail on windows. I had to build without it.

In fixing-nft ( that has no BINARYEN_TRAP_MODE ) i get this error  https://gist.github.com/kalwalt/80754a8e711593fd8ed7ef3d91e93038 running the nft_threejs_wasm.html so i need to add this line to avoid the error in the console and to get the example working in the correct manner.

> I built js & wasm files in windows environment based on this modified makem.js file here, based on here. This modified file is not in this pr.
 understood but in this way we can not works on the same basis. we should find a solution i think.

**Comment by kalwalt** [comment]
@misdake i will check also your makem.js, if it works on linux and Mac we can integrate it in the branch.

**Comment by kalwalt** [comment]
Tested the code: it works perfectly on desktop and smartphone. I think with better performances, but i have no a detailed comparisons for the moment...

**Comment by kalwalt** [comment]
I think we can exclude/include the line `-s "BINARYEN_TRAP_MODE='clamp'"` checking from which platform is executed the script. something like:

```js
if (process.platform === "linux") {
   FLAGS += ' -s BINARYEN_TRAP_MODE=clamp'
} 
```

**Comment by nicolocarpignoli** [comment]
On Mac:

I checkout on this branch
Ran `npm run build`
tried `nft_threejs_wasm.html`

Got error:

```
Uncaught RuntimeError: float unrepresentable in integer range
    at wasm-function[216]:0x9dd8
    at wasm-function[1086]:0x43b04
    at wasm-function[1087]:0x43b58
    at wasm-function[1088]:0x43cd0
    at wasm-function[1089]:0x43e1c
    at wasm-function[1209]:0x4c3ff
    at wasm-function[1165]:0x49c01
    at wasm-function[1166]:0x49d00
    at wasm-function[1167]:0x49d30
    at wasm-function[1316]:0x55e4b
```

**Comment by nicolocarpignoli** [comment]
> I think we can exclude/include the line `-s "BINARYEN_TRAP_MODE='clamp'"` checking from which platform is executed the script. Something like:
> 
> ```js
> if (process.platform === "linux") {
>    FLAGS += ' -s BINARYEN_TRAP_MODE=clamp'
> } 
> ```

Maybe modifies for linux are good also for Mac as they are UNIX both.
It's better in my opinion something like:

```
if (process.platform !== "win32") {
   	FLAGS += ' -s BINARYEN_TRAP_MODE=clamp'
}
```

https://stackoverflow.com/questions/8683895/how-do-i-determine-the-current-operating-system-with-node-js

**Comment by nicolocarpignoli** [comment]
@misdake @kalwalt 

In my opinion we have to 'fix' a version and continue working on that, without change the scope of our efforts.

Which version has the better performances between workers and wasm + workers? If it's possible to have metrics, we can then decide

**Comment by kalwalt** [comment]
> On Mac:
> 
> I checkout on this branch
> Ran `npm run build`
> tried `nft_threejs_wasm.html`
> 
> Got error:
> 
> ```
> Uncaught RuntimeError: float unrepresentable in integer range
>     at wasm-function[216]:0x9dd8
>     at wasm-function[1086]:0x43b04
>     at wasm-function[1087]:0x43b58
>     at wasm-function[1088]:0x43cd0
>     at wasm-function[1089]:0x43e1c
>     at wasm-function[1209]:0x4c3ff
>     at wasm-function[1165]:0x49c01
>     at wasm-function[1166]:0x49d00
>     at wasm-function[1167]:0x49d30
>     at wasm-function[1316]:0x55e4b
> ```

@nicolocarpignoli That's correct because the script not build with the BINARYEN option. That's bad because in mac you can not build with the right wasm at the moment because this error. I remember that you need to exclude the `-s BINARYEN_TRAP_MODE=clamp` line to build with emscripten.

**Comment by kalwalt** [comment]
Another question @nicolocarpignoli what result do you get with https://kalwalt.github.io/jsartoolkit5/examples/nft_threejs_wasm.html do you receive the same error?

**Comment by nicolocarpignoli** [comment]
> Another question @nicolocarpignoli what result do you get with https://kalwalt.github.io/jsartoolkit5/examples/nft_threejs_wasm.html do you receive the same error?

yes same error

**Comment by nicolocarpignoli** [comment]
Actually this can be a problem: one thing is to not be able to build in my (or other) machines, another thing is that the example builded and working for you, is not working on my chrome on mac...that's a real problem

**Comment by kalwalt** [comment]
> yes same error
Thank you @nicolocarpignoli !
I uploaded the examples but i receive an error (probably some error in the path of wasm?)

> Actually this can be a problem: one thing is to not be able to build in my (or other) machines, another thing is that the example builded and working for you, is not working on my chrome on mac...that's a real problem

You get the point @nicolocarpignoli !!

**Comment by kalwalt** [comment]
another question: Do you get the same error also with this example https://rgbuv.xyz/jsartoolkit_wasm/main_threejs_worker.html hosted by @misdake ?

**Comment by nicolocarpignoli** [comment]
> another question: Do you get the same error also with this example https://rgbuv.xyz/jsartoolkit_wasm/main_threejs_worker.html hosted by @misdake ?

nope, this one does not give that error!

**Comment by kalwalt** [comment]
> > another question: Do you get the same error also with this example https://rgbuv.xyz/jsartoolkit_wasm/main_threejs_worker.html hosted by @misdake ?
> 
> nope, this one does not give that error!

but in this comment ` I did some experiments to make it barely work in worker using your wasm build:` https://github.com/kalwalt/jsartoolkit5/pull/7#issuecomment-562906726 make me humbling a lot, i will try the makem.js used by @misdake to make a comparison.

**Comment by kalwalt** [comment]
The problem was my emscripten version, updated to the latest. with the latest version of emscripten the BINARYEN line is not needed. One note for who has to update emscripten, this command won't works:
```shell
# Fetch the latest registry of available tools.
./emsdk update
```
you need to `git pull ` instead and remeber to change the EMSCRIPTEN var in ./bashrc if you have set and point to the `upstream/emscripten` folder.

The example still not works can't find the error at the moment, @misdake maybe can you help me?

**Comment by kalwalt** [comment]
@nicolocarpignoli **nft_threejs_wasm.html** now works also for me without the BINARYEN line!

**Comment by kalwalt** [comment]
The updated makem.js script is based on the [gist](https://gist.github.com/misdake/ec0f67c3f50b0b89229d8e70ed77c37d) provided by @misdake.
It will be nice if someone can test under Mac and Windows,  @nicolocarpignoli @Carnaux can you?
i used the latest emscripten [emsdk](https://github.com/emscripten-core/emsdk/commit/1e42b446510ad27489bce58e3952ccaf4803fc68) we can use this as reference for everyone in the future, and update as emscripten emsdk receive important updates. 
I want also add in a near future a wiki section for basic use of emscripten with jsartoolkit5.

**Comment by Carnaux** [comment]
@kalwalt It's working on Windows!

**Comment by nicolocarpignoli** [comment]
@kalwalt I'm still getting the same error:

what I did:

* checked out on this branch
* ran npm run build
* run on chrome, on my mac, nft_threejs_wasm.html

**Comment by kalwalt** [comment]
> @kalwalt It's working on Windows!

great thanks!

@nicolocarpignoli this error?

`Uncaught RuntimeError: float unrepresentable in integer range`

But the project is build correctly? ( the last one question is very important because before wasn't possible to build under windows...) are you sure that you are using emscripten with the commit i noted in the first post? with upstream?

**Comment by kalwalt** [comment]
Anyway in the console i receive this warning: 

```js
artoolkitNft_wasm.js:1 wasm streaming compile failed: TypeError: Failed to execute 'compile' on 'WebAssembly': Incorrect response MIME type. Expected 'application/wasm'.
artoolkitNft_wasm.js:1 falling back to ArrayBuffer instantiation
```
but the code works maybe we need to do some modifications.

**Comment by kalwalt** [comment]
Maybe a stupid question @nicolocarpignoli , but you receive the same error with the **examples/nft_improved_worker/index.html**  example?

**Comment by kalwalt** [comment]
I will close this PR, but i merged the changes for the makem.js file into fixing-nft branch with this [commit](https://github.com/kalwalt/jsartoolkit5/pull/1/commits/3993f8786a92127dc95e146884ffa8f25af30471) 
We re-add support for wasm and wasm plus workers when we will setup a build chain as suggested by @ThorstenBux. This will simplify the build for different platforms.

**Pull request closed without merging**
