### PR TITLE
Adding --no-libar option in the build script

### PR DESCRIPTION
**Pull request by kalwalt**
From #44 . This PR will speed up the build process of the libs. If you have already build **libar.bc** with the command:

`npm run buil-local `

the second time run instead:

`npm run buil-local-no-libar`

libar.bc will not be build again saving time and effort.

Updated documentation and cleaned also makem.js by obsolete old part of code, fixed some lintings, and typos, in package.json and Readme.md.

Tested under linux OS (Ubuntu 18.04.03 LTS)

### CODE REVIEW

**Comment by kalwalt** [comment]
I think we need also to test under MacOs and Windows if possible.

**Comment by ThorstenBux** [comment]
Buildig on macOS :) but as we are using Docker to build it should behave the same no matter which OS

**Comment by kalwalt** [comment]
> Buildig on macOS :) but as we are using Docker to build it should behave the same no matter which OS

You are completely right!

**Comment by nicolocarpignoli** [comment]
it compiles on mac :) 

what is missing? test from Windows?

**Comment by kalwalt** [comment]
> it compiles on mac :)
> 
> what is missing? test from Windows?

yes, it is required a test under Windows OS, i'm wondering if this is possible under wine (with Ubuntu)...

**Comment by ThorstenBux** [comment]
I don’t think we need to test on Windows as said it is Docker. Should be fine. If not someone will open a PR

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by kalwalt** [comment]
ok, i will fix also some links as this [one](https://github.com/artoolkitx/jsartoolkit5/blob/244b2b23286403e78fa24805b34509dc5a88052f/examples/index.html#L35) that point to the old repository, and i will add a mention to the `tests` in the main folder project structure.

**Comment by kalwalt** [comment]
if i go to this link https://github.com/artoolkit/artoolkit5/blob/master/doc/Marker%20images/pinball.jpg seems that artoolkit/artoolkit5 is reborn! However, I wonder if it is better to focus on the 'new' repository **artoolkitx/artoolkit5**.

**Comment by kalwalt** [comment]
I think that is better to change those links, actually jsartoolkit5 is under the **artoolkitx** org so it has no sense to let those links pointing to **artoolkit**.

**Comment by kalwalt** [comment]
I'm going to merge this PR in my develop branch before send a PR to **artoolkitx/jsartoolkit5** @ThorstenBux  if you have nothing against it.

**Pull request merged**
